In [32]:
# Name: Siddharth Ghawate
# Roll no: 53
# Batch: TY IT A(A3)
# Assignmnet Title: FDS Lab Assignment 1
import numpy as np

In [ ]:
#Create a 2D array
arr1 = np.array([[1, 2, 3, 4, 5],[6,7,8,9,10]])
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
#Dimensions of the array
arr1.ndim

2

In [43]:
#Shape and size of the array
print(arr1.shape)
print(arr1.size)

(2, 5)
10


In [44]:
#Data type of the array
arr1.dtype

dtype('int64')

In [ ]:
#Arange and reshape
arr2=np.arange(10)
arr2
arr2.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
#array indexing
print(arr1[0, 1])
print(arr1[-1, -1])

2
10


In [ ]:
# Arithmetic Operations
a1 = np.array([[1, 2, 3], [4, 5, 6]])
a2 = np.array([[7, 8, 9], [10, 11, 12]])
#Addition
print(a1)
print("----------------")
print(a2)
print("----------------")
print(a1 + a2)

[[1 2 3]
 [4 5 6]]
----------------
[[ 7  8  9]
 [10 11 12]]
----------------
[[ 8 10 12]
 [14 16 18]]


In [55]:
#Subtraction
print(a1)
print("----------------")
print(a2)   
print("----------------")
print(a1 - a2)

[[1 2 3]
 [4 5 6]]
----------------
[[ 7  8  9]
 [10 11 12]]
----------------
[[-6 -6 -6]
 [-6 -6 -6]]


In [56]:
#Division
print(a1)   
print("----------------")
print(a2)
print("----------------")
print(a1 / a2)

[[1 2 3]
 [4 5 6]]
----------------
[[ 7  8  9]
 [10 11 12]]
----------------
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [57]:
#Multiplication
print(a1)
print("----------------")
print(a2)
print("----------------")
print(a1 * a2)

[[1 2 3]
 [4 5 6]]
----------------
[[ 7  8  9]
 [10 11 12]]
----------------
[[ 7 16 27]
 [40 55 72]]


In [58]:
#Argmax and Argmin
print("Argmax of a1:", np.argmax(a1))
print("Argmin of a1:", np.argmin(a1))

Argmax of a1: 5
Argmin of a1: 0


In [ ]:
#Linespace
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])