In [27]:
import numpy as np

In [28]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [29]:
arr1 = np.zeros(5)
arr2 = np.zeros(5).astype(int)
print(arr1,arr2)

[0. 0. 0. 0. 0.] [0 0 0 0 0]


In [30]:
ones_arr = np.ones(5).astype(int)
print(ones_arr)

[1 1 1 1 1]


In [31]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])
print("Array is:\n",arr3,'\n')

shap=np.shape(arr3)
print(shap,":Shape\n")

dime=np.ndim(arr3)
print(dime,":Dimension\n")

Array is:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]] 

(4, 3) :Shape

2 :Dimension

